//
// AuctionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

//import Foundation
//#if canImport(AnyCodable)
//import AnyCodable
//#endif
//
///** Multiple different slot types may be combined into a single request.  */
//public struct AuctionRequest: Codable, JSONEncodable, Hashable {
//
//    public var slots: Slots
//    /** An array of objects, each describing a product that should participate in the auction. */
//    public var products: [Product]
//    public var session: Session
//    /** An array of objects, each describing a vendor that should participate in the auction. */
//    public var vendors: [Vendor]
//    public var bannerOptions: AnyCodable?
//
//    public init(slots: Slots, products: [Product], session: Session, vendors: [Vendor], bannerOptions: AnyCodable?) {
//        self.slots = slots
//        self.products = products
//        self.session = session
//        self.vendors = vendors
//        self.bannerOptions = bannerOptions
//    }
//
//    public enum CodingKeys: String, CodingKey, CaseIterable {
//        case slots
//        case products
//        case session
//        case vendors
//        case bannerOptions
//    }
//
//    // Encodable protocol methods
//
//    public func encode(to encoder: Encoder) throws {
//        var container = encoder.container(keyedBy: CodingKeys.self)
//        try container.encode(slots, forKey: .slots)
//        try container.encode(products, forKey: .products)
//        try container.encode(session, forKey: .session)
//        try container.encode(vendors, forKey: .vendors)
//        try container.encode(bannerOptions, forKey: .bannerOptions)
//    }
//}

