//
// AuctionSlotsListings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuctionSlotsListings: Codable, JSONEncodable, Hashable {

    /** Topsort assigned ID for auction. Should be used in reporting impressions, clicks and purchases. */
    public var auctionId: String?
    /** Array of winner objects in order from highest to lowest bid. May be empty if there were no qualifying bids. */
    public var winners: [Winner]?

    public init(auctionId: String? = nil, winners: [Winner]? = nil) {
        self.auctionId = auctionId
        self.winners = winners
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case auctionId
        case winners
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(auctionId, forKey: .auctionId)
        try container.encodeIfPresent(winners, forKey: .winners)
    }
}

