//
// BannerOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The BannerOptions object specifies options to take into consideration when running a banner auction. */
public struct BannerOptions: Codable, JSONEncodable, Hashable {

    public enum Placement: String, Codable, CaseIterable {
        case homePage = "Home-page"
        case categoryPage = "Category-page"
        case searchPage = "Search-page"
    }
    public var placement: Placement?

    public init(placement: Placement? = nil) {
        self.placement = placement
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case placement
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(placement, forKey: .placement)
    }
}

