//
// BannersSlots.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The Slots object specifies how many auctions winners should be returned for each promotion type. The promotion types depend on the marketplace configuration. For banner ads, use the \&quot;bannerAds\&quot; key. */
public struct BannersSlots: Codable, JSONEncodable, Hashable {

    public var bannerAds: Int?

    public init(bannerAds: Int? = nil) {
        self.bannerAds = bannerAds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bannerAds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bannerAds, forKey: .bannerAds)
    }
}

