//
// ImpressionEventAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ImpressionEventAllOf: Encodable, JSONEncodable, Hashable {

    public var impressions: [Impression]
    /** RFC3339 formatted timestamp including UTC offset */
    public var occurredAt: Date?

    public init(impressions: [Impression], occurredAt: Date? = nil) {
        self.impressions = impressions
        self.occurredAt = occurredAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case impressions
        case occurredAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(impressions, forKey: .impressions)
        try container.encodeIfPresent(occurredAt, forKey: .occurredAt)
    }
}

