////
//// ListingsSlots.swift
////
//// Generated by openapi-generator
//// https://openapi-generator.tech
////
//
//import Foundation
//#if canImport(AnyCodable)
//import AnyCodable
//#endif
//
///** The Slots object specifies how many auctions winners should be returned for each promotion type. The promotion types depend on the marketplace configuration. For sponsored listings, use the \&quot;listings\&quot; key. */
//public struct ListingsSlots: Slots, Codable, JSONEncodable, Hashable {
//
//    public var listings: Int?
//
//    public init(listings: Int? = nil) {
//        self.listings = listings
//    }
//
//    public enum CodingKeys: String, CodingKey, CaseIterable {
//        case listings
//    }
//
//    // Encodable protocol methods
//
//    public func encode(to encoder: Encoder) throws {
//        var container = encoder.container(keyedBy: CodingKeys.self)
//        try container.encodeIfPresent(listings, forKey: .listings)
//    }
//}
//
