//
// Placement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Placement: Codable, JSONEncodable, Hashable {

    /** A marketplace assigned name for a page. */
    public var page: String
    /** A marketplace defined name for a page part. */
    public var location: String?

    public init(page: String, location: String? = nil) {
        self.page = page
        self.location = location
    }

    private enum CodingKeys: String, CodingKey, CaseIterable {
        case page
        case location
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(page, forKey: .page)
        try container.encodeIfPresent(location, forKey: .location)
    }
}

