//
// PurchaseEventAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PurchaseEventAllOf: Codable, JSONEncodable, Hashable {

    /** The marketplace assigned ID for the order. */
    public var id: String
    /** RFC3339 formatted timestamp including UTC offset */
    public var purchasedAt: Date
    /** Items purchased. */
    public var items: [PurchaseItem]

    public init(id: String, purchasedAt: Date, items: [PurchaseItem]) {
        self.id = id
        self.purchasedAt = purchasedAt
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case purchasedAt
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(purchasedAt, forKey: .purchasedAt)
        try container.encode(items, forKey: .items)
    }
}

