//
// PurchaseEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The consumer has purchased some products. */
public struct PurchaseEvent: Encodable, JSONEncodable, Hashable {
    /** The marketplace assigned ID for the order. */
    public var id: String
    /** Timestamp from when was the purchase completed */
    public var purchasedAt: Date
    /** Items purchased. */
    public var items: [PurchaseItem]

    public init(id: String, purchasedAt: Date = Date(), items: [PurchaseItem]) {
        self.id = id
        self.purchasedAt = purchasedAt
        self.items = items
    }

    private enum CodingKeys: String, CodingKey, CaseIterable {
        case eventType
        case session
        case id
        case purchasedAt
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        let session = Session(sessionId: getSessionId())
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode("Purchase", forKey: .eventType)
        try container.encode(session, forKey: .session)
        try container.encode(id, forKey: .id)
        try container.encode(purchasedAt, forKey: .purchasedAt)
        try container.encode(items, forKey: .items)
    }
}
