//
// AuctionRequestHomepageStandaloneBanners.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuctionRequestHomepageStandaloneBanners: Codable, JSONEncodable, Hashable {

    public var slots: BannersSlots
    public var session: Session
    public var bannerOptions: AnyCodable?

    public init(slots: BannersSlots, session: Session, bannerOptions: AnyCodable?) {
        self.slots = slots
        self.session = session
        self.bannerOptions = bannerOptions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slots
        case session
        case bannerOptions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(slots, forKey: .slots)
        try container.encode(session, forKey: .session)
        try container.encode(bannerOptions, forKey: .bannerOptions)
    }
}

