//
// AuctionRequestSponsoredListings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuctionRequestSponsoredListings: Codable, JSONEncodable, Hashable {

    public var slots: ListingsSlots
    /** An array of objects, each describing a product that should participate in the auction. */
    public var products: [Product]
    public var session: Session

    public init(slots: ListingsSlots, products: [Product], session: Session) {
        self.slots = slots
        self.products = products
        self.session = session
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slots
        case products
        case session
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(slots, forKey: .slots)
        try container.encode(products, forKey: .products)
        try container.encode(session, forKey: .session)
    }
}

