//
// AuctionSlots.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuctionSlots: Codable, JSONEncodable, Hashable {

    public var listings: AuctionSlotsListings?

    public init(listings: AuctionSlotsListings? = nil) {
        self.listings = listings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case listings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(listings, forKey: .listings)
    }
}

