//
// Auction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Auction: Codable, JSONEncodable, Hashable {

    public var slots: AuctionSlots?

    public init(slots: AuctionSlots? = nil) {
        self.slots = slots
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slots
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(slots, forKey: .slots)
    }
}

