//
// AuctionRequestGeneralBanners.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AuctionRequestGeneralBanners: Codable, JSONEncodable, Hashable {

    public var slots: BannersSlots
    /** An array of objects, each describing a product that should participate in the auction. */
    public var products: [Product]
    /** An array of objects, each describing a vendor that should participate in the auction. */
    public var vendors: [Vendor]
    public var session: Session
    public var bannerOptions: BannerOptions

    public init(slots: BannersSlots, products: [Product], vendors: [Vendor], session: Session, bannerOptions: BannerOptions) {
        self.slots = slots
        self.products = products
        self.vendors = vendors
        self.session = session
        self.bannerOptions = bannerOptions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case slots
        case products
        case vendors
        case session
        case bannerOptions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(slots, forKey: .slots)
        try container.encode(products, forKey: .products)
        try container.encode(vendors, forKey: .vendors)
        try container.encode(session, forKey: .session)
        try container.encode(bannerOptions, forKey: .bannerOptions)
    }
}

