//
// Product.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Product: Codable, JSONEncodable, Hashable {

    public var productId: String
    public var quality: Float?

    public init(productId: String, quality: Float? = nil) {
        self.productId = productId
        self.quality = quality
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productId
        case quality
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(productId, forKey: .productId)
        try container.encodeIfPresent(quality, forKey: .quality)
    }
}

