//
// PurchaseEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The consumer has purchased some products. */
public struct PurchaseEvent: Codable, JSONEncodable, Hashable {

    public enum EventType: String, Codable, CaseIterable {
        case impression = "Impression"
        case click = "Click"
        case purchase = "Purchase"
    }
    /** Discriminator for the type of event. */
    public var eventType: EventType
    public var session: Session
    /** The marketplace assigned ID for the order. */
    public var id: String
    /** RFC3339 formatted timestamp including UTC offset */
    public var purchasedAt: Date
    /** Items purchased. */
    public var items: [PurchaseItem]

    public init(eventType: EventType, session: Session, id: String, purchasedAt: Date, items: [PurchaseItem]) {
        self.eventType = eventType
        self.session = session
        self.id = id
        self.purchasedAt = purchasedAt
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventType
        case session
        case id
        case purchasedAt
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventType, forKey: .eventType)
        try container.encode(session, forKey: .session)
        try container.encode(id, forKey: .id)
        try container.encode(purchasedAt, forKey: .purchasedAt)
        try container.encode(items, forKey: .items)
    }
}

