//
// Vendor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Vendor: Codable, JSONEncodable, Hashable {

    public var vendorId: String

    public init(vendorId: String) {
        self.vendorId = vendorId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case vendorId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(vendorId, forKey: .vendorId)
    }
}

